-- Migration 007b: Force RLS for table owners
-- Ensures RLS policies apply even to table owners (not just superusers)

-- Enable FORCE ROW LEVEL SECURITY on all user-owned tables
-- This makes RLS policies apply to the table owner as well

ALTER TABLE works FORCE ROW LEVEL SECURITY;
ALTER TABLE assets FORCE ROW LEVEL SECURITY;
ALTER TABLE authors FORCE ROW LEVEL SECURITY;
ALTER TABLE annotations FORCE ROW LEVEL SECURITY;
ALTER TABLE cards FORCE ROW LEVEL SECURITY;
ALTER TABLE review_logs FORCE ROW LEVEL SECURITY;
ALTER TABLE collections FORCE ROW LEVEL SECURITY;
ALTER TABLE edges FORCE ROW LEVEL SECURITY;
ALTER TABLE presets FORCE ROW LEVEL SECURITY;
ALTER TABLE activities FORCE ROW LEVEL SECURITY;
ALTER TABLE boards FORCE ROW LEVEL SECURITY;
ALTER TABLE strokes FORCE ROW LEVEL SECURITY;
ALTER TABLE blobs_meta FORCE ROW LEVEL SECURITY;
ALTER TABLE device_blobs FORCE ROW LEVEL SECURITY;
ALTER TABLE replication_jobs FORCE ROW LEVEL SECURITY;
ALTER TABLE user_settings FORCE ROW LEVEL SECURITY;
