/**
 * Session types: time-bounded blocks of practice
 * Sessions group attempts and provide context for learning
 */

import type {
  SessionId,
  UserId,
  AttemptId,
  ConceptNodeId,
  ExerciseTemplateId,
} from "./ids";
import type { AttemptMode } from "./enums";

// =============================================================================
// Session
// =============================================================================

/**
 * A practice session: a time-bounded block of learning activity
 */
export interface Session {
  /** Unique identifier */
  id: SessionId;

  /** User who conducted this session */
  userId: UserId;

  /** Mode of practice for this session */
  mode: AttemptMode;

  // ===== Timing =====

  /** When the session started */
  startedAt: string;

  /** When the session ended (null if in progress) */
  endedAt?: string;

  /** Planned duration in minutes (for cram sessions) */
  plannedDurationMinutes?: number;

  /** Actual duration in seconds */
  actualDurationSeconds?: number;

  // ===== Targeting =====

  /** Concept IDs this session focuses on (for cram/targeted practice) */
  targetConceptIds?: ConceptNodeId[];

  /** Exercise IDs this session focuses on (for cram/targeted practice) */
  targetExerciseIds?: ExerciseTemplateId[];

  // ===== Progress =====

  /** IDs of attempts made during this session */
  attemptIds: AttemptId[];

  /** Number of exercises completed */
  exercisesCompleted: number;

  /** Number of exercises planned (if applicable) */
  exercisesPlanned?: number;

  // ===== User Reflection =====

  /** User's reflection note at the end of the session */
  reflectionNote?: string;

  /** User's mood/energy rating at start (1-5) */
  startMoodRating?: number;

  /** User's mood/energy rating at end (1-5) */
  endMoodRating?: number;

  /** User's perceived difficulty of the session (1-5) */
  sessionDifficulty?: number;

  // ===== Session State =====

  /** Current status of the session */
  status: "active" | "paused" | "completed" | "abandoned";

  /** When this session was created */
  createdAt: string;

  /** When this session was last updated */
  updatedAt: string;
}

/**
 * Input for starting a session
 */
export interface SessionStart {
  userId: UserId;
  mode: AttemptMode;
  plannedDurationMinutes?: number;
  targetConceptIds?: ConceptNodeId[];
  targetExerciseIds?: ExerciseTemplateId[];
  startMoodRating?: number;
}

/**
 * Input for completing a session
 */
export interface SessionComplete {
  id: SessionId;
  endedAt: string;
  reflectionNote?: string;
  endMoodRating?: number;
  sessionDifficulty?: number;
}

// =============================================================================
// Session Summary
// =============================================================================

/**
 * Summary statistics for a completed session
 */
export interface SessionSummary {
  session: Session;

  /** Total number of attempts */
  totalAttempts: number;

  /** Number of correct attempts */
  correctAttempts: number;

  /** Average accuracy across all attempts */
  averageAccuracy: number;

  /** Total active time (excluding pauses) */
  totalActiveSeconds: number;

  /** Concepts covered in this session */
  conceptsCovered: ConceptNodeId[];

  /** Exercises completed */
  exercisesCompleted: ExerciseTemplateId[];

  /** Exercises that were struggles (low accuracy or multiple attempts) */
  struggles: ExerciseTemplateId[];

  /** Exercises that went well (high accuracy, good time) */
  successes: ExerciseTemplateId[];
}

// =============================================================================
// Session Streaks
// =============================================================================

/**
 * User's practice streak information
 */
export interface PracticeStreak {
  userId: UserId;

  /** Current consecutive days with practice */
  currentStreak: number;

  /** Longest ever streak */
  longestStreak: number;

  /** Last practice date (ISO string) */
  lastPracticeDate: string;

  /** Total practice days */
  totalPracticeDays: number;

  /** Practice days this week */
  daysThisWeek: number;

  /** Total practice minutes this week */
  minutesThisWeek: number;
}

// =============================================================================
// Session Planning
// =============================================================================

/**
 * A suggested session plan (generated by the system)
 */
export interface SessionPlan {
  mode: AttemptMode;

  /** Suggested duration in minutes */
  suggestedDurationMinutes: number;

  /** Exercises to include, in suggested order */
  exerciseQueue: Array<{
    templateId: ExerciseTemplateId;
    variantId?: string;
    reason: string; // e.g., "due for review", "new concept", "related to struggle"
    priority: number;
  }>;

  /** Concepts that will be covered */
  conceptsCovered: ConceptNodeId[];

  /** Estimated difficulty */
  estimatedDifficulty: "easy" | "medium" | "hard";

  /** Reasoning for this plan */
  planningNotes?: string;
}
